# Global Travis CI step definitions that will be used by all jobs unless
# explicitly overriden in the jobs.include matrix.

language: python
dist: xenial
# We need to be able to install packages.
sudo: required
python: "3.6"

services:
  - docker
  - redis-server

addons:
  postgresql: "10"

before_install:
  # NOTE: We need to manually install ElasticSearch since we want to control
  # the exact version we use instead of relying on the version shipped by
  # Travis CI's python image.
  # XXX: Version 6.7.0 should be used, but it doesn't work on Travis.
  - curl -sSL -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.0.deb
  - sudo dpkg -i --force-confnew elasticsearch-6.6.0.deb
  - sudo service elasticsearch restart

install: pip install tox

script: tox -e $TOX_ENV

after_success:
  - pip install codecov
  - codecov -e TOX_ENV

# Build stages.
jobs:
  include:
    - stage: test
      env:
        - TOX_ENV=py36
        # Set environment variables with information how to use the required
        # services.
        - RESOLWE_POSTGRESQL_USER=postgres
        - RESOLWE_POSTGRESQL_PORT=5432
        - RESOLWE_ES_PORT=9200
        - RESOLWE_REDIS_PORT=6379
        # NOTE: We need to disable SECCOMP as it is not supported on Travis CI.
        - RESOLWE_DOCKER_DISABLE_SECCOMP=1
    - stage: test
      python: "3.7"
      env:
        - TOX_ENV=py37
        # Set environment variables with information how to use the required
        # services.
        - RESOLWE_POSTGRESQL_USER=postgres
        - RESOLWE_POSTGRESQL_PORT=5432
        - RESOLWE_ES_PORT=9200
        - RESOLWE_REDIS_PORT=6379
        # NOTE: We need to disable SECCOMP as it is not supported on Travis CI.
        - RESOLWE_DOCKER_DISABLE_SECCOMP=1

    # NOTE: We undo almost all global Travis CI step definitions to ensure the
    # following Tox environments are run without access to any service.
    - stage: test
      env: TOX_ENV=docs
      services: []
      addons: {}
      before_install: skip
      after_success: skip
    - stage: test
      env: TOX_ENV=linters
      services: []
      addons: {}
      before_install: skip
      after_success: skip
    - stage: test
      env: TOX_ENV=packaging
      services: []
      addons: {}
      before_install: skip
      after_success: skip

    # NOTE: We undo many global Travis CI step definitions to ensure the
    # following Tox environment only has access to the PostgreSQL service.
    - stage: test
      env:
        - TOX_ENV=migrations
        # Set environment variables with information how to use the PostgreSQL
        # service.
        - RESOLWE_POSTGRESQL_USER=postgres
        - RESOLWE_POSTGRESQL_PORT=5432
      services: []
      before_install: skip
      after_success: skip

    # NOTE: We undo all the global Travis CI step definitions to ensure
    # building of source and wheel distributions is performed in a clean
    # environment.
    - stage: release
      services: []
      addons: {}
      before_install: skip
      # Project uses setuptools_scm to determine the version from a SCM tag.
      install: pip install setuptools_scm
      script: skip
      # NOTE: Due to the way Travis CI currently works, setting
      # 'after_success: skip' would also result in skipping the deploy step.
      # A work-around is to execute a dummy echo command.
      # More info at: https://github.com/travis-ci/travis-ci/issues/8337.
      after_success: echo "Skipping..."
      deploy:
        provider: pypi
        user: genialis-bot
        password:
          secure: "bLtFX2U2ZZVbV50/iNvvnVHyMaG4O5J7NJMe5qdcQbPVou76hcavPhfcNiLAiqqwGhYdMArkL8mavBgC4glfG9dSqJYAevbNsKSEoz1ShS10ZkSwGgBKUNXhtOp1Iw49w6jvIxB1nRckStlIaPlyuGisjTC2Tk1CbZY/OVvFSqVBsdDiFPGZGOwnadrOTtx+IR0+3CTt3nBH7CqDiIW4K4s4DZxfhtEfWSgXTMViObMuOd0HE03zFIs3+mMFxCOHMsH9SzJAf9q2ZMmBaSEiUEQQckqhj3ScSNwX+GcXeSCXIjwk6xuNmZnp4L1u8dhwTzmTlFsv/ygXHxNMJIABM397e7sKuS2wDiYfyaijjSCDklK2z/w69WQFPFtnH5/pn8h2OeV7Ma3OXLoZUKcXwmq1zpQ2SnuEbTIXcANuakD2ThpqXEqvdia6rBDaxj/1APalik38+52sFPlqx/Q53yILZnesg/TmrgrjEoJj6AvbXHxq7IMJLf6YILLK2WuORXGLsZx5s6RXWBbeao6Wc+8S95FzzAG+g4euB6wT8zjYCSeiS+4CWux5nrlfiXkp9yIdfVQHGmFvyZ0gCjK7wPWno6hNaiWicxEsCMIsoKAaz3PD+crmZ076VDQerBP85gQZydU8oY4fA/sWknOqkmSsEWy6BGUEkLdqk9ZJadU="
        distributions: sdist bdist_wheel
        on:
          # Enable deploying tags. By default, Travis CI only deploys from the
          # master branch.
          tags: true
      # Only build releases for tags starting with a Semantic Versioning 2.0
      # compatible version.
      if: tag =~ ^\d+\.\d+\.\d+
